/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package vn.viettuts.detaiso10.view;

/**
 *
 * @author PC
 */
public class Helpview extends javax.swing.JPanel {

    /**
     * Creates new form Helppanel
     */
    public Helpview() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();

        setBackground(new java.awt.Color(135, 206, 250));

        jLabel1.setBackground(new java.awt.Color(255, 255, 224));
        jLabel1.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        jLabel1.setText("Hướng dẫn sử dụng:");

        jLabel2.setBackground(new java.awt.Color(255, 255, 224));
        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N

        jTextArea1.setColumns(20);
        jTextArea1.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jTextArea1.setRows(5);
        jTextArea1.setText("Sản phẩm:\n   1.Thêm: thêm mới sản phẩm vào cửa hàng(chưa có ảnh)\n   2.Sửa: sửa thông tin sản phẩm và cập nhật lại\n   3.Xóa: xóa sản phẩm khỏi danh sách sản phẩm\n   4.Sắp xếp: trỏ chuột vào cột bất kì để sắp xếp danh sách \n   5.Clear: Đặt lại nội dung trong bảng thông tin về null\n   6.Thêm ảnh: chọn ảnh giày để thêm ảnh cho giày được thêm ở trên\n   7.Tìm kiếm: tìm kiếm theo tên hoặc size\nKhách hàng:\n  1.Thêm: thêm mới khách hàng vào danh sách khách hàng\n  2.Sửa: sửa thông tin khách hàng và cập nhật lại\n  3.Xóa: xóa khách hàng khỏi danh sách khách hàng\n  4.Sắp xếp: trỏ chuột vào cột bất kì để sắp xếp danh sách khách hàng\n  5.Clear: Đặt lại nội dung của khách hàng trong bảng hiển thị thông tin về null\nMua hàng:(chọn size  giày và khách hàng  trong phần mua hàng)\n  1.Thêm(+): thêm 1 sản phẩm vào hóa đơn mua hàng\n  2.Xóa(-):  xóa bớt 1 sản phẩm khỏi hóa đơn mua hàng\n  3.Khách trả: nhập số tiền khách trả cho toàn bộ hóa đơn\n  4.Pay: Thực hiện tính toán và xuất hóa đơn (nếu mua thành công)\n  5.Clear: Đặt lại thông tin hóa đơn về null\nAbout store:\n   1.Thêm: thêm mới nhân viên vào cửa hàng(chưa có ảnh)\n   2.Sửa: sửa thông tin nhân viên và cập nhật lại\n   3.Xóa: xóa nhân viên khỏi cửa hàng\n   4.Clear: Đặt lại nội dung trong bảng thông tin về null\n   5.Thêm ảnh: chọn ảnh nhân viên để thêm ảnh cho nhân viên được thêm ở trên\n   6.Total staff: Tính tổng số nhân viên đang làm việc cho cửa hàng\nThống kê:\n  1.Biểu đồ: Hiện biểu đồ cho người dùng xem\n  2.Các loại biểu đồ: \n     a) Biểu đồ thống kê số lượng từng loại giày có trong cửa hàng(biểu đồ cột)\n     b) Biểu đồ thống kê size giày được yêu thích(prefered size, biểu đồ tròn)\n     c) Biểu đồ thống kê số lượng bán được từng loại giày (biểu đồ tròn)");
        jScrollPane1.setViewportView(jTextArea1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 888, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 558, Short.MAX_VALUE))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    // End of variables declaration//GEN-END:variables
}
