package vn.viettuts.detaiso10.view;

import java.awt.Dimension;
import java.awt.Toolkit;
import java.util.ArrayList;
import java.util.List;
import vn.viettuts.detaiso10.bean.Danhmucbean;
import vn.viettuts.detaiso10.controller.Chuyenmanhinhcontroller;
import vn.viettuts.detaiso10.view.Loginview;
import vn.viettuts.detaiso10.view.Shopview;


public class Shopview extends javax.swing.JFrame {
    public Shopview() {
        initComponents();
        Chuyenmanhinhcontroller controller = new Chuyenmanhinhcontroller(chaomungpanel);
        List<Danhmucbean> listItem= new ArrayList<>();
        listItem.add(new Danhmucbean("sanpham",sppanel,sanphambutton));
        listItem.add(new Danhmucbean("muahang",mhpanel,muahangbutton));
        listItem.add(new Danhmucbean("khachhang",khpanel,khachhangbutton));
        listItem.add(new Danhmucbean("thongke",tkpanel,thongkebutton));
        listItem.add(new Danhmucbean("about",abpanel,aboutbutton));
        listItem.add(new Danhmucbean("help",hpanel,helpbutton));
        listItem.add(new Danhmucbean("manhinhchinh",mhcpanel,manhinhchinhbutton));
        String kind = listItem.get(0).getKind();
        controller.setEvent(listItem);
        
        Dimension screenSize = Toolkit.getDefaultToolkit().getScreenSize();
        Dimension windowSize = this.getSize();
        // Tính toán vị trí mới để đặt cửa sổ ở giữa màn hình
        int x = (screenSize.width - windowSize.width) / 2;
        int y = (screenSize.height - windowSize.height) / 2;
        this.setLocation(x, y);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        framepanel = new javax.swing.JPanel();
        menupanel = new javax.swing.JPanel();
        mhcpanel = new javax.swing.JPanel();
        manhinhchinhbutton = new javax.swing.JButton();
        abpanel = new javax.swing.JPanel();
        aboutbutton = new javax.swing.JButton();
        khpanel = new javax.swing.JPanel();
        khachhangbutton = new javax.swing.JButton();
        sppanel = new javax.swing.JPanel();
        sanphambutton = new javax.swing.JButton();
        mhpanel = new javax.swing.JPanel();
        muahangbutton = new javax.swing.JButton();
        tkpanel = new javax.swing.JPanel();
        thongkebutton = new javax.swing.JButton();
        hpanel = new javax.swing.JPanel();
        helpbutton = new javax.swing.JButton();
        dxpanel = new javax.swing.JPanel();
        dangxuatbutton = new javax.swing.JButton();
        chaomungpanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1095, 660));

        framepanel.setBackground(new java.awt.Color(255, 255, 224));
        framepanel.setMinimumSize(new java.awt.Dimension(0, 0));
        framepanel.setPreferredSize(new java.awt.Dimension(1080, 660));
        framepanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        menupanel.setBackground(new java.awt.Color(153, 0, 153));
        menupanel.setPreferredSize(new java.awt.Dimension(180, 620));

        mhcpanel.setBackground(new java.awt.Color(0, 0, 0));
        mhcpanel.setPreferredSize(new java.awt.Dimension(180, 100));

        manhinhchinhbutton.setBackground(new java.awt.Color(199, 21, 133));
        manhinhchinhbutton.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        manhinhchinhbutton.setForeground(new java.awt.Color(255, 255, 255));
        manhinhchinhbutton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/outline_home_white_24dp.png"))); // NOI18N
        manhinhchinhbutton.setText("Trang chủ");
        manhinhchinhbutton.setPreferredSize(new java.awt.Dimension(180, 115));

        javax.swing.GroupLayout mhcpanelLayout = new javax.swing.GroupLayout(mhcpanel);
        mhcpanel.setLayout(mhcpanelLayout);
        mhcpanelLayout.setHorizontalGroup(
            mhcpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, mhcpanelLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(manhinhchinhbutton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        mhcpanelLayout.setVerticalGroup(
            mhcpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(manhinhchinhbutton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        abpanel.setBackground(new java.awt.Color(0, 0, 0));
        abpanel.setPreferredSize(new java.awt.Dimension(180, 55));

        aboutbutton.setBackground(new java.awt.Color(199, 21, 133));
        aboutbutton.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        aboutbutton.setForeground(new java.awt.Color(255, 255, 255));
        aboutbutton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/outline_error_outline_white_24dp.png"))); // NOI18N
        aboutbutton.setText("About store");
        aboutbutton.setPreferredSize(new java.awt.Dimension(180, 70));
        aboutbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aboutbuttonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout abpanelLayout = new javax.swing.GroupLayout(abpanel);
        abpanel.setLayout(abpanelLayout);
        abpanelLayout.setHorizontalGroup(
            abpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, abpanelLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(aboutbutton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        abpanelLayout.setVerticalGroup(
            abpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, abpanelLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(aboutbutton, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        khpanel.setBackground(new java.awt.Color(0, 0, 0));
        khpanel.setPreferredSize(new java.awt.Dimension(180, 55));

        khachhangbutton.setBackground(new java.awt.Color(199, 21, 133));
        khachhangbutton.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        khachhangbutton.setForeground(new java.awt.Color(255, 255, 255));
        khachhangbutton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/outline_perm_identity_white_24dp.png"))); // NOI18N
        khachhangbutton.setText("Khách hàng");
        khachhangbutton.setPreferredSize(new java.awt.Dimension(180, 70));

        javax.swing.GroupLayout khpanelLayout = new javax.swing.GroupLayout(khpanel);
        khpanel.setLayout(khpanelLayout);
        khpanelLayout.setHorizontalGroup(
            khpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, khpanelLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(khachhangbutton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        khpanelLayout.setVerticalGroup(
            khpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, khpanelLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(khachhangbutton, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        sppanel.setBackground(new java.awt.Color(0, 0, 0));
        sppanel.setPreferredSize(new java.awt.Dimension(180, 55));

        sanphambutton.setBackground(new java.awt.Color(199, 21, 133));
        sanphambutton.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        sanphambutton.setForeground(new java.awt.Color(255, 255, 255));
        sanphambutton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/outline_storefront_white_24dp.png"))); // NOI18N
        sanphambutton.setText("Sản phẩm");
        sanphambutton.setPreferredSize(new java.awt.Dimension(180, 70));
        sanphambutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sanphambuttonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout sppanelLayout = new javax.swing.GroupLayout(sppanel);
        sppanel.setLayout(sppanelLayout);
        sppanelLayout.setHorizontalGroup(
            sppanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, sppanelLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(sanphambutton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        sppanelLayout.setVerticalGroup(
            sppanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(sanphambutton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        mhpanel.setBackground(new java.awt.Color(0, 0, 0));
        mhpanel.setPreferredSize(new java.awt.Dimension(180, 55));

        muahangbutton.setBackground(new java.awt.Color(199, 21, 133));
        muahangbutton.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        muahangbutton.setForeground(new java.awt.Color(255, 255, 255));
        muahangbutton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/outline_add_shopping_cart_white_24dp.png"))); // NOI18N
        muahangbutton.setText("Mua hàng");
        muahangbutton.setPreferredSize(new java.awt.Dimension(180, 70));

        javax.swing.GroupLayout mhpanelLayout = new javax.swing.GroupLayout(mhpanel);
        mhpanel.setLayout(mhpanelLayout);
        mhpanelLayout.setHorizontalGroup(
            mhpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, mhpanelLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(muahangbutton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        mhpanelLayout.setVerticalGroup(
            mhpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, mhpanelLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(muahangbutton, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        tkpanel.setBackground(new java.awt.Color(0, 0, 0));
        tkpanel.setPreferredSize(new java.awt.Dimension(180, 55));

        thongkebutton.setBackground(new java.awt.Color(199, 21, 133));
        thongkebutton.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        thongkebutton.setForeground(new java.awt.Color(255, 255, 255));
        thongkebutton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/outline_paid_white_24dp.png"))); // NOI18N
        thongkebutton.setText("Thống kê");
        thongkebutton.setPreferredSize(new java.awt.Dimension(180, 70));

        javax.swing.GroupLayout tkpanelLayout = new javax.swing.GroupLayout(tkpanel);
        tkpanel.setLayout(tkpanelLayout);
        tkpanelLayout.setHorizontalGroup(
            tkpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, tkpanelLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(thongkebutton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        tkpanelLayout.setVerticalGroup(
            tkpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, tkpanelLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(thongkebutton, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        hpanel.setBackground(new java.awt.Color(0, 0, 0));
        hpanel.setPreferredSize(new java.awt.Dimension(180, 55));

        helpbutton.setBackground(new java.awt.Color(199, 21, 133));
        helpbutton.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        helpbutton.setForeground(new java.awt.Color(255, 255, 255));
        helpbutton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/outline_help_white_24dp.png"))); // NOI18N
        helpbutton.setText("Help");
        helpbutton.setPreferredSize(new java.awt.Dimension(180, 70));

        javax.swing.GroupLayout hpanelLayout = new javax.swing.GroupLayout(hpanel);
        hpanel.setLayout(hpanelLayout);
        hpanelLayout.setHorizontalGroup(
            hpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, hpanelLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(helpbutton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        hpanelLayout.setVerticalGroup(
            hpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, hpanelLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(helpbutton, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        dxpanel.setBackground(new java.awt.Color(0, 0, 0));
        dxpanel.setPreferredSize(new java.awt.Dimension(180, 55));

        dangxuatbutton.setBackground(new java.awt.Color(199, 21, 133));
        dangxuatbutton.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        dangxuatbutton.setForeground(new java.awt.Color(255, 255, 255));
        dangxuatbutton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/outline_reply_white_24dp.png"))); // NOI18N
        dangxuatbutton.setText("Đăng xuất");
        dangxuatbutton.setPreferredSize(new java.awt.Dimension(180, 43));
        dangxuatbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dangxuatbuttonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout dxpanelLayout = new javax.swing.GroupLayout(dxpanel);
        dxpanel.setLayout(dxpanelLayout);
        dxpanelLayout.setHorizontalGroup(
            dxpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, dxpanelLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(dangxuatbutton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        dxpanelLayout.setVerticalGroup(
            dxpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dxpanelLayout.createSequentialGroup()
                .addComponent(dangxuatbutton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout menupanelLayout = new javax.swing.GroupLayout(menupanel);
        menupanel.setLayout(menupanelLayout);
        menupanelLayout.setHorizontalGroup(
            menupanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mhcpanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(sppanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(khpanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(mhpanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(abpanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(tkpanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(hpanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(dxpanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        menupanelLayout.setVerticalGroup(
            menupanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menupanelLayout.createSequentialGroup()
                .addComponent(mhcpanel, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addComponent(sppanel, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addComponent(khpanel, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addComponent(mhpanel, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addComponent(abpanel, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addComponent(tkpanel, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addComponent(hpanel, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addComponent(dxpanel, javax.swing.GroupLayout.DEFAULT_SIZE, 43, Short.MAX_VALUE))
        );

        framepanel.add(menupanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        chaomungpanel.setBackground(new java.awt.Color(255, 255, 224));
        chaomungpanel.setMaximumSize(new java.awt.Dimension(1060, 620));
        chaomungpanel.setPreferredSize(new java.awt.Dimension(900, 660));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/ledneon28515.jpg"))); // NOI18N
        jLabel1.setText("jLabel1");
        jLabel1.setPreferredSize(new java.awt.Dimension(900, 620));

        javax.swing.GroupLayout chaomungpanelLayout = new javax.swing.GroupLayout(chaomungpanel);
        chaomungpanel.setLayout(chaomungpanelLayout);
        chaomungpanelLayout.setHorizontalGroup(
            chaomungpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        chaomungpanelLayout.setVerticalGroup(
            chaomungpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        framepanel.add(chaomungpanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 0, -1, 620));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(framepanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(15, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(framepanel, javax.swing.GroupLayout.PREFERRED_SIZE, 620, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(20, Short.MAX_VALUE))
        );

        getAccessibleContext().setAccessibleName("Tuấn-Phúc shoes shop");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void sanphambuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sanphambuttonActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_sanphambuttonActionPerformed

    private void aboutbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aboutbuttonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_aboutbuttonActionPerformed

    private void dangxuatbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dangxuatbuttonActionPerformed
        // TODO add your handling code here:
        if(this.isVisible()){
            this.setVisible(false);
            Loginview loginView= new Loginview();
            loginView.setVisible(true);
        }
    }//GEN-LAST:event_dangxuatbuttonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton aboutbutton;
    private javax.swing.JPanel abpanel;
    private javax.swing.JPanel chaomungpanel;
    private javax.swing.JButton dangxuatbutton;
    private javax.swing.JPanel dxpanel;
    private javax.swing.JPanel framepanel;
    private javax.swing.JButton helpbutton;
    private javax.swing.JPanel hpanel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton khachhangbutton;
    private javax.swing.JPanel khpanel;
    private javax.swing.JButton manhinhchinhbutton;
    private javax.swing.JPanel menupanel;
    private javax.swing.JPanel mhcpanel;
    private javax.swing.JPanel mhpanel;
    private javax.swing.JButton muahangbutton;
    private javax.swing.JButton sanphambutton;
    private javax.swing.JPanel sppanel;
    private javax.swing.JButton thongkebutton;
    private javax.swing.JPanel tkpanel;
    // End of variables declaration//GEN-END:variables

    
}
